apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
  namespace: observability
data:
  locustfile.py: |
    import time
    from locust import HttpUser, task

    class QuickstartUser(HttpUser):
        @task
        def getUser(self):
            self.client.get("/AsistenteVirtualOutbound/api/v1/outbound/getUser?user_id=apineda")
  locustfile2.py: |
    import time
    from locust import HttpUser, task

    class QuickstartUser1(HttpUser):
        @task
        def getTemplates(self):
            self.client.get("/AsistenteVirtualOutbound/api/v1/outbound/getTemplates")
