apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
  namespace: quality-control-and-testing
data:
  locustfile.py: |
    import time
    from locust import HttpUser, task

    class QuickstartUser(HttpUser):
        @task
        def getUser(self):
            self.client.get("http://api-elastic.158.23.251.48.nip.io/WeatherForecast/")
  locustfile2.py: |
    import time
    from locust import HttpUser, task

    class QuickstartUser1(HttpUser):
        @task
        def getTemplates(self):
            self.client.get("/AsistenteVirtualOutbound/api/v1/outbound/getTemplates")
