apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust-ingress
  namespace: quality-control-and-testing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: locust.158.23.246.62.nip.io
    http:
      paths:
      - backend:
          service:
            name: locust-master
            port:
              number: 8089
        path: /locust(/|$)(.*)
        pathType: Prefix
  ingressClassName: nginx
