apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: observability
  name: kibana
spec:
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.12.0
        env:
        - name: ELASTICSEARCH_URL
          value: http://elastic.158.23.246.19.nip.io/
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: kibana-secret-user-elastic
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secret-user-elastic
              key: password
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP