apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-storage-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-storage-manager
subjects:
  - kind: Group
    name: <ID_DEL_GRUPO_ENTRA_ID>
    apiGroup: rbac.authorization.k8s.io