apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
 name: jaeger-srv
 namespace: observability
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.observability:9200
        username: elastic
        password: aeFhyzK1El6ZNcm7ArCa
      cmdlineParams:
        es.tls.enabled: true
        es.tls.skip-host-verify: true