apiVersion: v1
kind: ConfigMap
metadata:
  namespace: observability
  name: kibana-config
  labels:
    component: kibana
data:
  elasticsearch_username: elastic
  elasticsearch_password: KXKH4FXjeXUn1VAdD5s6