apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: observability
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template: 
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.15.3
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 4Gi
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node