apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: observability
  labels:
    component: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: Demo-Elastic
    node.name: Master
    path.data: /var/lib/elasticsearch/data
    http:
      host: 0.0.0.0
      port: 9200
    bootstrap.memory_lock: true
    transport.host: 127.0.0.1
    xpack.license.self_generated.type: basic
    # Enable xpack.security which is provided in basic subscription
    xpack.security.enabled: true
    # Disable unused xpack features 
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
    xpack.ml.enabled: false
    xpack.security.authc.realms:
      native.realm1:
          order: 0
          cache.ttl: 10m 
  ES_JAVA_OPTS: -Xms2g -Xmx4g