apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-outbound-api-map
  namespace: outbound
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;

    error_log  /var/log/nginx/error.log debug;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
        log_format upstream_time '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" '
        'rt="$request_time" uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        access_log  /var/log/nginx/access.log;

        sendfile        on;
        keepalive_timeout  120;

        upstream outbound-api {
            server 127.0.0.1:5020;
        }

        server {
          server_name _;
          listen 80;

          location / {
              return 200 'OK';
              default_type text/plain;
          }

          location /AsistenteVirtualOutbound {
              fastcgi_read_timeout 600;
              fastcgi_send_timeout 600;
              fastcgi_connect_timeout 600;
              proxy_connect_timeout 600;
              proxy_send_timeout 600;
              proxy_read_timeout 600;
              send_timeout 600;
              proxy_set_header        Host $host;
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        X-Forwarded-Proto $scheme;
              proxy_set_header        X-Forwarded-Host $http_host;
              proxy_pass              http://outbound-api;
          }
        }
    }
