apiVersion: v1
data:
  templates.json: ewogICAgInJlc3BvbnNlIiA6IFsKICAgICAgewogICAgICAgICJ0ZW1wbGF0ZV9uYW1lIjogInBydWViYSIsCiAgICAgICAgImJvZHlfcGFyYW1zIjogMSwKICAgICAgICAibGFuZ3VhZ2UiOiAiZXNfTVgiLAogICAgICAgICJhcmVhX2dyb3VwIjogIlFldHNvbCIsCiAgICAgICAgIndvcmtzcGFjZV9ncm91cCI6ICJRZXRzb2wiLAogICAgICAgICJjYXRlZ29yeSI6ICJDYWxlbnRkb3JlcyIsCiAgICAgICAgImNvbnRlbnRfc2lkIjogIkhYMTMyZmQwYWJkZTU1YWEzYmZlOTBiMGVjMWRjNjliNDkiLAogICAgICAgICJzaG93X3dlYnNlcnZpY2UiOiB0cnVlCiAgICAgIH0KICAgIF0KfQ==
kind: Secret
metadata:
  name: secret-templates-twilio
  namespace: outbound
type: Opaque
