# Source: cost-analyzer/templates/grafana-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubecost-grafana-clusterrolebinding
  labels:
    app: grafana
    release: kubecost
    heritage: Helm
subjects:
  - kind: ServiceAccount
    name: kubecost-grafana
    namespace: observability
roleRef:
  kind: ClusterRole
  name: kubecost-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io