# Source: cost-analyzer/templates/grafana-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubecost-grafana
  namespace: observability
  labels:
    app: grafana
    release: kubecost
    heritage: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "c3Ryb25ncGFzc3dvcmQ="
  ldap-toml: ""