apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin-binding
  namespace: <NAMESPACE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
subjects:
  - kind: Group
    name: <ID_DEL_GRUPO_ENTRA_ID>
    apiGroup: rbac.authorization.k8s.io